responses:
  job_application_response:
    - >-
      Siamo sempre alla ricerca di nuovi talenti! Dai un'occhiata alle
      posizioni aperte [qui](/ads): per candidarti ti basta registrarti sul
      sito e allegare il tuo curriculum al profilo.
